// angular/tictactoe/src/app/game/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { StateService } from '../../services/state.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {
  constructor(private stateService: StateService, private router: Router) {}

  ngOnInit() {}

  resetGame() {
    this.stateService.reset();
    this.router.navigate(['new']);
  }
}

<p><strong>Number of movements:</strong> {{ (stateService.state$ | async).numberMovements }}</p>
<button
  class="btn"
  [class.disabled]="(stateService.state$ | async).numberMovements === 0"
  (click)="resetGame()"
>
  Reset game
</button>

// react/tictactoe/src/components/Tictactoe/Footer.jsx
import React from 'react';
import '../../assets/styles/Footer.css';

const Footer = props => (
  <footer>
    <p>
      <strong>Number of movements:</strong> {props.numberMovements}
    </p>
    <button
      className={'btn' + (props.numberMovements === 0 ? ' disabled' : '')}
      onClick={() => props.resetGame()}
    >
      Reset game
    </button>
  </footer>
);

export default Footer;
