// angular/tictactoe/src/app/game/components/game/game.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { StateService } from '../../services/state.service';
import { HttpService } from 'src/app/services/http.service';
import { State } from '../../game.models';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css']
})
export class GameComponent implements OnInit {
  status: string;
  stateService: StateService;
  playerName: string;

  constructor(route: ActivatedRoute, stateService: StateService, httpService: HttpService) {
    this.status = 'fetching';
    this.stateService = stateService;
    this.playerName = '';
    if (route.snapshot.data.continue) {
      httpService.getSavedGame().subscribe(
        (state: State) => {
          stateService.state = state;
          this.status = 'success';
        },
        error => {
          this.status = error.statusText;
        }
      );
    } else {
      stateService.reset();
      this.status = 'success';
    }
  }

  ngOnInit() {}

  handleSubmitClick() {
    this.stateService.state.playerName = this.playerName;
  }
}

<div class="loader" *ngIf="status === 'fetching'"></div>
<div *ngIf="status === 'success'">
  <form *ngIf="(stateService.state$ | async).playerName === ''">
    <input type="text" name="playerName" placeholder="Player Name" [(ngModel)]="playerName" />
    <button type="submit" (click)="handleSubmitClick()">Submit</button>
  </form>

  <div *ngIf="(stateService.state$ | async).playerName !== ''">
    <app-header></app-header>
    <app-board></app-board>
    <app-footer></app-footer>
  </div>
</div>
<h3 *ngIf="status !== 'success' && status !== 'fetching'">
  Error getting state from server. The error was: {{ status }}
</h3>

// react/tictactoe/src/components/Tictactoe/Game.jsx
import React from 'react';
import { Redirect } from 'react-router-dom';
import { connect } from 'react-redux';
import { playPosition, resetGame, fetchState, newPlayer } from '../../reducers/actions';
import '../../assets/styles/Game.css';
import Header from './Header';
import Board from './Board';
import Footer from './Footer';

class Game extends React.Component {
  constructor(props) {
    super(props);
    this.redirect = false;
    this.state = {
      playerName: ''
    };
  }

  handlePlayerInputChange = event => {
    this.setState({ playerName: event.target.value });
  };

  handlePlayerSubmit = event => {
    event.preventDefault();
    this.props.dispatch(newPlayer(this.state.playerName));
  };

  handleSquareClick = (rowNumber, columnNumber) => {
    this.props.dispatch(
      playPosition(
        rowNumber,
        columnNumber,
        this.props.turn,
        this.props.values,
        this.props.numberMovements,
        this.props.winner
      )
    );
  };

  resetGame = () => {
    this.props.dispatch(resetGame());
    this.redirect = true;
  };

  componentDidMount() {
    if (this.props.continue) {
      this.props.dispatch(fetchState());
    } else {
      this.resetGame();
    }
  }

  render() {
    if (this.redirect) {
      this.redirect = false;
      return <Redirect to="/new" />;
    }
    if (this.props.continue && this.props.fetch.fetching) {
      return <div className="game">Loading the saved game...</div>;
    } else if (this.props.continue && !this.props.fetch.fetching && this.props.fetch.error) {
      console.log(this.props.fetch.error);
      return (
        <div className="game">
          Error getting state from server. The error was: {this.props.fetch.error.toString()}
        </div>
      );
    } else {
      if (this.props.playerName !== '') {
        return (
          <div>
            <Header
              playerName={this.props.playerName}
              winner={this.props.winner}
              turn={this.props.turn}
            />
            <Board
              winner={this.props.winner}
              values={this.props.values}
              handleSquareClick={this.handleSquareClick}
            />
            <Footer numberMovements={this.props.numberMovements} resetGame={this.resetGame} />
          </div>
        );
      } else {
        return (
          <header className="game">
            <form onSubmit={this.handlePlayerSubmit}>
              <input
                type="text"
                placeholder="Player Name"
                name="name"
                value={this.state.playerName}
                onChange={this.handlePlayerInputChange}
              />
              <button type="submit">Submit</button>
            </form>
          </header>
        );
      }
    }
  }
}

function mapStateToProps(state) {
  return {
    values: state.values,
    turn: state.turn,
    numberMovements: state.numberMovements,
    winner: state.winner,
    playerName: state.playerName,
    fetch: state.fetch
  };
}
export default connect(mapStateToProps)(Game);
