// react/tictactoe/src/components/SavedGame.jsx
import React from 'react';
import { withRouter } from 'react-router-dom';
import '../assets/styles/SavedGame.css';

class SavedGame extends React.Component {
  handleContinueClick = () => this.props.history.push('continue/' + this.props.savedGame.id);

  handleDeleteClick = () => this.props.deleteGame(this.props.savedGame.id);

  render() {
    return (
      <div className="saved">
        <span>{this.props.savedGame.name}</span>
        <button className="saved" onClick={() => this.handleContinueClick()}>
          Continue
        </button>
        <button className="saved" onClick={() => this.handleDeleteClick()}>
          Delete
        </button>
      </div>
    );
  }
}

export default withRouter(SavedGame);

// angular/tictactoe/src/app/components/saved-game/saved-game.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { SavedGame } from 'src/app/game/game.models';
import { StateService } from 'src/app/game/services/state.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-saved-game',
  templateUrl: './saved-game.component.html',
  styleUrls: ['./saved-game.component.css']
})
export class SavedGameComponent implements OnInit {
  @Input() savedGame: SavedGame;

  constructor(private stateService: StateService, private router: Router) {}

  ngOnInit() {}

  handleContinueClick() {
    this.router.navigate(['continue/' + this.savedGame.id]);
  }

  handleDeleteClick() {
    this.stateService.deleteGame(this.savedGame.id);
  }
}

<div>
  <span>{{ savedGame.name }}</span>
  <button (click)="handleContinueClick()">Continue</button>
  <button (click)="handleDeleteClick()">Delete</button>
</div>
